webdriver.base.url=https://www.saucedemo.com
webdriver.driver=chrome
webdriver.chrome.driver=../drivers/chromedriver-win64/chromedriver.exe
chrome.switches=--no-sandbox,--disable-dev-shm-usage,--disable-gpu,--window-size=1920,1080,--disable-features=PasswordLeakDetection,--no-first-run
chrome.preferences=credentials_enable_service:false,profile.password_manager_enabled:false,profile.password_manager_leak_detection:false
serenity.take.screenshots=AFTER_EACH_STEP
serenity.report.dir=target/site/serenity
serenity.project.name=NTT Data - SauceDemo E2E Tests
webdriver.timeouts.implicitlywait=5000
